# -*- coding: utf-8 -*-
"""Data Analyst internship Task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1obbN-mXdkXcvfTwXRiucjdH3deM1RMP0

# Task 1: Data Cleaning and Preprocessing

## Mall Customer Segmentation Dataset

### Summary
The Mall Customer Segmentation dataset includes details like Customer ID, Age, Gender, Annual Income and Spending Score. By analysing this type of dataset helps in understanding customer behaviour, tastes and preferences which eventually support adopting effective marketing strategies.

### Data Loading and Intial Overview
"""

# Loading the Dataset
import numpy as np
import pandas as pd
df = pd.read_csv(r"C:\Users\DHANYA\Downloads\archive (5).zip")
print("Dataset is loaded successfully!")

df

#  Display Column Information and Non-Null Counts
df.info()

"""### Data Pre-processing"""

# Checking missing values
df.isnull().sum()

"""#### Note
- So it is confirmed that the given dataset is free from missing values.
"""

# Droping Duplicate Values
df.drop_duplicates()

# Checking duplicated values
df.duplicated().sum()

"""#### Note
- This means that the dataset is free from duplicates.
"""

# Checking Data Types
df.dtypes

"""#### Note
- The dataset is clean with appropriate data types - numeric features for analysis and on categorical variable (Gender) for grouping.

### Export as CSV
"""

# Exporting Cleaned Dataset
df.to_csv("cleaned_mall_customer_segmentation_dataset.csv", index=False)
print("CSV file successfully exported!")

"""## Short Summary of Task:1

#### In Task 1, I performed essential data cleaning steps to prepare the dataset for analysis:
- Verified that the dataset has **no missing values**.
- Confirmed that there are **no duplicate records**.
- Checked and validated **data types**, ensuring numeric features and one categorical variable (Gender) are correctly structured.
- Finally, I exported the **cleaned dataset**.
"""

